[package]
name = "pkgar"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plain = "0.2.3"
sodalite = "0.3.0"

[dependencies.sha2]
version = "0.8.0"
default-features = false

[features]
default = ["std"]
std = []
