[package]
name = "pkgar"
version = "0.1.6"
description = "Redox Package Archive"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Wesley Hershberger <mggmugginsmc@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/pkgar"
edition = "2018"

[dependencies]
plain = "0.2.3"
pkgar-keys = { path = "../pkgar-keys" }
sodiumoxide = { version = "0.2.5", default_features = false }

[dependencies.clap]
version = "2.33.0"
optional = true

[dependencies.blake3]
version = "0.2.1"
default-features = false
features = ["rayon"]

[features]
default = ["clap", "std"]
std = []

